//CHECKSTYLE:OFF FileLength
/*
 * Project and Training 1: Oware Game - Computer Science, Berner Fachhochschule
 */
package ch.bfh.oware.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Set;

import org.junit.jupiter.api.Test;

/**
 * This test class can be used for testing classes implementing the {@link Board} interface. The name of the class to
 * be used in the tests can be adjusted within the private method {@link BoardTest#createBoard(int, int)}.
 */
public class BoardTest {

	private Board createBoard(int size, int seeds) {
		return new MyBoardClass(size, seeds);
	}

	//CHECKSTYLE:OFF MethodLength
	@Test
	public void testExampleFromGit() {

		// CHECKSTYLE:OFF MagicNumber
		Board board = createBoard(6, 4);
		assertEquals(board.getSize(), 6);
		assertEquals(board.getInitialSeeds(), 4);

		assertEquals(board.countSeeeds(1, 1), 4);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 4);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 4);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 4);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 4, 5, 6)));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 4, 5, 6)));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 4);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 4);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 5);
		assertEquals(board.countSeeeds(2, 1), 5);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 4, 6)));
		assertFalse(board.getMoves(1).contains(5));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 4, 5, 6)));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 6);
		assertEquals(board.countSeeeds(1, 1), 5);
		assertEquals(board.countSeeeds(1, 2), 5);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 5);
		assertEquals(board.countSeeeds(2, 1), 5);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 4, 6)));
		assertFalse(board.getMoves(1).contains(5));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 4, 5)));
		assertFalse(board.getMoves(2).contains(6));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 5);
		assertEquals(board.countSeeeds(1, 2), 5);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 6);
		assertEquals(board.countSeeeds(2, 1), 6);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 6);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 5, 6)));
		assertFalse(board.getMoves(1).contains(4));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 4, 5)));
		assertFalse(board.getMoves(2).contains(6));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 4);
		assertEquals(board.countSeeeds(1, 1), 6);
		assertEquals(board.countSeeeds(1, 2), 6);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 6);
		assertEquals(board.countSeeeds(2, 1), 6);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 6);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 5);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 5, 6)));
		assertFalse(board.getMoves(1).contains(4));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 5, 6)));
		assertFalse(board.getMoves(2).contains(4));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 6);
		assertEquals(board.countSeeeds(1, 2), 6);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 7);
		assertEquals(board.countSeeeds(2, 2), 7);
		assertEquals(board.countSeeeds(2, 3), 7);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 6);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 5)));
		assertFalse(board.getMoves(1).contains(4));
		assertFalse(board.getMoves(1).contains(6));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 4, 5)));
		assertFalse(board.getMoves(2).contains(6));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 5);
		assertEquals(board.countSeeeds(1, 1), 7);
		assertEquals(board.countSeeeds(1, 2), 7);
		assertEquals(board.countSeeeds(1, 3), 6);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 7);
		assertEquals(board.countSeeeds(2, 2), 7);
		assertEquals(board.countSeeeds(2, 3), 7);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.getMoves(1).containsAll(Set.of(1, 2, 3, 4)));
		assertFalse(board.getMoves(1).contains(5));
		assertFalse(board.getMoves(1).contains(6));
		assertTrue(board.getMoves(2).containsAll(Set.of(1, 2, 3, 4, 6)));
		assertFalse(board.getMoves(2).contains(5));
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());
	}

	@Test
	public void testOneOne() {

		Board board = createBoard(1, 1);
		assertEquals(board.getSize(), 1);
		assertEquals(board.getInitialSeeds(), 1);

		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertTrue(board.gameOver());
	}

	@Test
	public void testOneTwo() {

		Board board = createBoard(1, 2);
		assertEquals(board.getSize(), 1);
		assertEquals(board.getInitialSeeds(), 2);

		assertEquals(board.countSeeeds(1, 1), 2);
		assertEquals(board.countSeeeds(2, 1), 2);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(2, 1), 3);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2,1);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertTrue(board.gameOver());
	}

	@Test
	public void testTwoOne() {

		Board board = createBoard(2, 1);
		assertEquals(board.getSize(), 2);
		assertEquals(board.getInitialSeeds(), 1);

		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 3);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(2, 1), 2);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(2, 1), 3);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertTrue(board.gameOver());
	}

	@Test
	public void testSixFour() {

		Board board = createBoard(6, 4);
		assertEquals(board.getSize(), 6);
		assertEquals(board.getInitialSeeds(), 4);

		assertEquals(board.countSeeeds(1, 1), 4);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 4);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 4);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 4);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 5);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 4);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 4);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 5);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 5);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 6);
		assertEquals(board.countSeeeds(1, 4), 6);
		assertEquals(board.countSeeeds(1, 5), 6);
		assertEquals(board.countSeeeds(1, 6), 5);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 5);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 6);
		assertEquals(board.countSeeeds(1, 4), 6);
		assertEquals(board.countSeeeds(1, 5), 6);
		assertEquals(board.countSeeeds(1, 6), 5);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 5);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 7);
		assertEquals(board.countSeeeds(1, 5), 7);
		assertEquals(board.countSeeeds(1, 6), 6);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 7);
		assertEquals(board.countSeeeds(2, 3), 6);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 5);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 7);
		assertEquals(board.countSeeeds(1, 5), 7);
		assertEquals(board.countSeeeds(1, 6), 6);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 8);
		assertEquals(board.countSeeeds(2, 3), 6);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 5);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 8);
		assertEquals(board.countSeeeds(1, 6), 7);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 9);
		assertEquals(board.countSeeeds(2, 3), 7);
		assertEquals(board.countSeeeds(2, 4), 6);
		assertEquals(board.countSeeeds(2, 5), 6);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 8);
		assertEquals(board.countSeeeds(1, 6), 7);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 10);
		assertEquals(board.countSeeeds(2, 3), 7);
		assertEquals(board.countSeeeds(2, 4), 6);
		assertEquals(board.countSeeeds(2, 5), 6);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 8);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 11);
		assertEquals(board.countSeeeds(2, 3), 8);
		assertEquals(board.countSeeeds(2, 4), 7);
		assertEquals(board.countSeeeds(2, 5), 7);
		assertEquals(board.countSeeeds(2, 6), 5);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 8);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 12);
		assertEquals(board.countSeeeds(2, 3), 8);
		assertEquals(board.countSeeeds(2, 4), 7);
		assertEquals(board.countSeeeds(2, 5), 7);
		assertEquals(board.countSeeeds(2, 6), 5);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 8);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 12);
		assertEquals(board.countSeeeds(2, 3), 8);
		assertEquals(board.countSeeeds(2, 4), 7);
		assertEquals(board.countSeeeds(2, 5), 7);
		assertEquals(board.countSeeeds(2, 6), 5);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 0);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 9);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 9);
		assertEquals(board.countSeeeds(2, 4), 8);
		assertEquals(board.countSeeeds(2, 5), 8);
		assertEquals(board.countSeeeds(2, 6), 6);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 9);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 9);
		assertEquals(board.countSeeeds(2, 4), 8);
		assertEquals(board.countSeeeds(2, 5), 8);
		assertEquals(board.countSeeeds(2, 6), 6);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 9);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 9);
		assertEquals(board.countSeeeds(2, 4), 8);
		assertEquals(board.countSeeeds(2, 5), 8);
		assertEquals(board.countSeeeds(2, 6), 6);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 9);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 9);
		assertEquals(board.countSeeeds(2, 4), 8);
		assertEquals(board.countSeeeds(2, 5), 8);
		assertEquals(board.countSeeeds(2, 6), 6);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 9);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 10);
		assertEquals(board.countSeeeds(2, 4), 9);
		assertEquals(board.countSeeeds(2, 5), 8);
		assertEquals(board.countSeeeds(2, 6), 6);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 9);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 10);
		assertEquals(board.countSeeeds(2, 4), 9);
		assertEquals(board.countSeeeds(2, 5), 8);
		assertEquals(board.countSeeeds(2, 6), 6);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 10);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 10);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 10);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 10);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 10);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 10);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 10);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 11);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 11);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 11);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 11);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 11);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 0);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 12);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 3);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 12);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 12);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 12);
		assertEquals(board.countSeeeds(2, 5), 9);
		assertEquals(board.countSeeeds(2, 6), 7);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 13);
		assertEquals(board.countSeeeds(2, 5), 10);
		assertEquals(board.countSeeeds(2, 6), 8);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 13);
		assertEquals(board.countSeeeds(2, 5), 10);
		assertEquals(board.countSeeeds(2, 6), 8);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 13);
		assertEquals(board.countSeeeds(2, 5), 10);
		assertEquals(board.countSeeeds(2, 6), 8);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 3);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 14);
		assertEquals(board.countSeeeds(2, 5), 11);
		assertEquals(board.countSeeeds(2, 6), 9);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 14);
		assertEquals(board.countSeeeds(2, 5), 11);
		assertEquals(board.countSeeeds(2, 6), 9);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 15);
		assertEquals(board.countSeeeds(2, 5), 12);
		assertEquals(board.countSeeeds(2, 6), 9);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 15);
		assertEquals(board.countSeeeds(2, 5), 12);
		assertEquals(board.countSeeeds(2, 6), 9);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 2);
		assertFalse(board.gameOver());

		board.play(2, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 3);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 4);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 4);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 3);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 5);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 5);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 2);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 6);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 6);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 7);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 14);
		assertEquals(board.countSeeeds(2, 6), 11);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 8);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 15);
		assertEquals(board.countSeeeds(2, 6), 12);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 9);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 15);
		assertEquals(board.countSeeeds(2, 6), 12);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 16);
		assertEquals(board.countSeeeds(2, 6), 13);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 16);
		assertEquals(board.countSeeeds(2, 6), 13);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 3);
		assertEquals(board.countSeeeds(2, 5), 17);
		assertEquals(board.countSeeeds(2, 6), 13);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 3);
		assertEquals(board.countSeeeds(2, 5), 17);
		assertEquals(board.countSeeeds(2, 6), 13);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 4);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 18);
		assertEquals(board.countSeeeds(2, 6), 14);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 18);
		assertEquals(board.countSeeeds(2, 6), 14);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 4);
		assertFalse(board.gameOver());

		board.play(2, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 4);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 5);
		assertEquals(board.countSeeeds(1, 4), 4);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 3);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 6);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 8);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 8);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 7);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 8);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 8);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 8);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 9);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 10);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 16);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 2);
		assertEquals(board.countSeeeds(2, 6), 17);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 2);
		assertEquals(board.countSeeeds(2, 6), 17);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 3);
		assertEquals(board.countSeeeds(2, 6), 17);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 3);
		assertEquals(board.countSeeeds(2, 6), 17);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 18);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 18);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 5);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 19);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 19);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 10);
		assertFalse(board.gameOver());

		board.play(2, 6);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 5);
		assertEquals(board.countSeeeds(1, 5), 4);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 2);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 6);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 2);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 6);
		assertEquals(board.countSeeeds(1, 5), 5);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 7);
		assertEquals(board.countSeeeds(1, 5), 6);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 7);
		assertEquals(board.countSeeeds(1, 5), 6);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 3);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 10);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 7);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 4);
		assertEquals(board.countSeeeds(2, 4), 3);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 12);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 7);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 4);
		assertEquals(board.countSeeeds(2, 4), 3);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 12);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 3);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 4);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 4);
		assertEquals(board.countSeeeds(2, 3), 5);
		assertEquals(board.countSeeeds(2, 4), 4);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 5);
		assertEquals(board.countSeeeds(2, 3), 6);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 6);
		assertEquals(board.countSeeeds(2, 3), 6);
		assertEquals(board.countSeeeds(2, 4), 5);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 7);
		assertEquals(board.countSeeeds(2, 4), 6);
		assertEquals(board.countSeeeds(2, 5), 2);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 7);
		assertEquals(board.countSeeeds(2, 4), 6);
		assertEquals(board.countSeeeds(2, 5), 2);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 3);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 7);
		assertEquals(board.countSeeeds(2, 5), 3);
		assertEquals(board.countSeeeds(2, 6), 2);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 7);
		assertEquals(board.countSeeeds(2, 5), 3);
		assertEquals(board.countSeeeds(2, 6), 2);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 16);
		assertFalse(board.gameOver());

		board.play(2, 4);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 5);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 3);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 20);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 6);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 4);
		assertEquals(board.countSeeeds(2, 6), 3);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 20);
		assertFalse(board.gameOver());

		board.play(2, 5);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 7);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 20);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 8);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 20);
		assertFalse(board.gameOver());

		board.play(2, 6);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 9);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertFalse(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 10);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertFalse(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 14);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 16);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 2);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 16);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 3);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 3);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 4);
		assertEquals(board.countSeeeds(2, 4), 2);
		assertEquals(board.countSeeeds(2, 5), 1);
		assertEquals(board.countSeeeds(2, 6), 1);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 3);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 3);
		assertEquals(board.countSeeeds(2, 5), 2);
		assertEquals(board.countSeeeds(2, 6), 2);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 3);
		assertEquals(board.countSeeeds(2, 5), 2);
		assertEquals(board.countSeeeds(2, 6), 2);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 4);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 1);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 3);
		assertEquals(board.countSeeeds(2, 6), 3);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 2);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 3);
		assertEquals(board.countSeeeds(2, 6), 3);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 5);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 3);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 4);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 4);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 6);
		assertEquals(board.countSeeeds(1, 1), 1);
		assertEquals(board.countSeeeds(1, 2), 5);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertFalse(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 6);
		assertEquals(board.countSeeeds(1, 3), 1);
		assertEquals(board.countSeeeds(1, 4), 1);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertFalse(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 2);
		assertEquals(board.countSeeeds(1, 4), 2);
		assertEquals(board.countSeeeds(1, 5), 1);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 3);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 2);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 0);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 2);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 3);
		assertEquals(board.countSeeeds(1, 5), 2);
		assertEquals(board.countSeeeds(1, 6), 1);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 4);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 3);
		assertEquals(board.countSeeeds(1, 6), 2);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 18);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 5);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 20);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(2, 1);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 3);
		assertEquals(board.countSeeeds(2, 1), 0);
		assertEquals(board.countSeeeds(2, 2), 1);
		assertEquals(board.countSeeeds(2, 3), 1);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertTrue(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertEquals(board.getScore(1), 20);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.gameOver());

		board.play(1, 6);
		assertEquals(board.countSeeeds(1, 1), 0);
		assertEquals(board.countSeeeds(1, 2), 0);
		assertEquals(board.countSeeeds(1, 3), 0);
		assertEquals(board.countSeeeds(1, 4), 0);
		assertEquals(board.countSeeeds(1, 5), 0);
		assertEquals(board.countSeeeds(1, 6), 0);
		assertEquals(board.countSeeeds(2, 1), 1);
		assertEquals(board.countSeeeds(2, 2), 0);
		assertEquals(board.countSeeeds(2, 3), 0);
		assertEquals(board.countSeeeds(2, 4), 1);
		assertEquals(board.countSeeeds(2, 5), 0);
		assertEquals(board.countSeeeds(2, 6), 0);
		assertEquals(board.getScore(1), 24);
		assertEquals(board.getScore(2), 22);
		assertFalse(board.hasMoves(1));
		assertTrue(board.hasMoves(2));
		assertTrue(board.gameOver());
	}

}
